insurancepremium_insurancecalculator:
  view:
    templateRootPath: 'EXT:insurnace_premium/Resources/Private/Templates/'
    partialRootPath: 'EXT:insurnace_premium/Resources/Private/Partials/'
    layoutRootPath:  'EXT:insurnace_premium/Resources/Private/Layouts/'
  persistence:
    storagePid: 3
  settings:
    ajaxPageTypeNum: 5953554
  features:
    ignoreAllEnableFieldsInBe: true
